# This file describes a Fastly Compute package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["nisse@tnfgruppen.com"]
cloned_from = "https://github.com/fastly/compute-starter-kit-javascript-empty"
description = ""
language = "javascript"
manifest_version = 3
name = "edgeIO"
service_id = "BsgFmfRH1icLRvXd8NiUO0"

[scripts]
  build = "npm run build"
  post_init = "npm install"
